### ISSUE TITLE
Separate the JS player for local preview [feature request]

### ISSUE THREAD

**Issue by hupili** [asciinema/asciinema.org#121]
I think it's a good feature to be able to view the recorded clips locally and decide whether to upload or not (or even better, modify before upload because I may have incidentally put my sensitive data on screen).

I already did some small modification of ascii.io-cli to allow choice of upload/ delete. When I come to this project, it's hard for me to separate the JS player out. I'm not familiar with RoR. It's hard for me to figure out how things are stitched together.

Another use case of the local JS player is for presentation without network connection. The quality of ascii.io demo is very high. I very much want to use it for next presentation.

**Comment by sickill** [comment]
Ability to record to local file, replay in terminal, edit and then upload has just been added. See [1.0 release post](http://blog.asciinema.org/post/one-point-o/).
