### ISSUE TITLE
No way to consolidate accounts created by logging in with github and twitter

### ISSUE THREAD

**Issue by doherty** [asciinema/asciinema.org#124]
You offer two methods of logging in. Once you've created an account with Github, say, there's no way to add an association to your Twitter account. If you log in with Twitter the next time, it actually creates a 2nd account for you.
- There should be a way to associate both a Github account _and_ a Twitter account to your ascii.io account, so you don't have to try to remember which one you used the first time you logged in. This is the standard reason to not use so-called "social" logins.
- There should be a way to delete your account, and all your uploads on the settings page.

**Comment by revolter** [comment]
It's funny that, now, [Persona was just deprecated](https://bugzilla.mozilla.org/page.cgi?id=persona_deprecated.html).

**Comment by sickill** [comment]
@revolter It's sad, not funny. Anyway, asciinema.org haven't been using Persona for a while now, so this doesn't affect us.

**Comment by bittner** [comment]
I'm not sure if there is a newer issue for consolidating accounts (I didn't find any, sorry!).

Even as of today, it doesn't seem to be possible to associate several email addresses to a single account, i.e. add new email addresses in the [user settings page](https://asciinema.org/user/edit). Is that something that has been suggested or requested in the past?

**Comment by sickill** [comment]
@bittner I've been thinking about adding ability to assign multiple email addresses to user accounts. While I've been busy with other issues I still think this would be useful to quite a number of users. Feel free to open separate for this, and we can discuss further there 👍
