### ISSUE TITLE
Starting from a specific playback point

### ISSUE THREAD

**Issue by hupili** [asciinema/asciinema.org#142]
It's helpful to be able to start from middle of a record. e.g. 

```
http://asciinema.org/a/5970?t=3:20
http://asciinema.org/a/5970#t=3:20
```

This enables more efficient sharing.

**Comment by sickill** [comment]
There's related issues in player's repo: https://github.com/asciinema/asciinema-player/issues/13
Implementing it first in the player will enable us to add this feature asciinema.org.

**Comment by sickill** [comment]
Works now: https://asciinema.org/a/5970?t=3:20
@hupili can you test?

**Comment by hupili** [comment]
@sickill  works perfectly! Thanks for keeping on improving this cool service!
