### ISSUE TITLE
Please don't remove Github sign-in

### ISSUE THREAD

**Issue by komidore64** [asciinema/asciinema.org#147]
I have nothing against Mozilla Persona, though I don't use it, but I'd like it if you didn't remove sign-ins via Github. Since I already have a Github account, I'd prefer not to create an account for something else if I can help it.

Add as many sign-ins as possible, but please don't remove previous methods if it can be helped. How am I supposed to access my old asciicasts now?

**Comment by ryzhovau** [comment]
Looks like I can't control over my [account](https://asciinema.org/~ryzhovau) which was [created](https://yadi.sk/i/pj6mM2YAf9fYd) with Github sign-in.

I can't sign-in with Github account and can't assign my old token to the new asciinema account. What should I do?

**Comment by sickill** [comment]
Just login with the email you have assigned to your account, which is ryzhovau at gmail.

**Comment by ryzhovau** [comment]
How simple. Sorry for the stupid question.

**Comment by jiriks74** [comment]
Hi,
I'd like to ask what your decision on OIDC was. I have a self-hosted instance which I'd like to connect to my OIDC server. This would allow me to add users without enabling signups and removing users I don't want on asciinema anymore.

I tried to look into the docs but I haven't found any mention of being able to use OIDC so I guess you threw out the idea?
