### ISSUE TITLE
Embedding recordings as gif or png

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema.org#152]
This would allow people to embed their asciicasts in README files as static "screenshot"-like PNGs or animated GIFs.

Some helpful resources:

https://gist.github.com/lmjabreu/922530
http://blog.animatron.com/post/73949058475/rendering

**Comment by schickling** [comment]
+1

**Comment by sickill** [comment]
PNG support is already there. You can now embed asciicast in your READMEs, issues, comments here on Github. See: https://twitter.com/asciinema/status/581517854887002113

@tav thanks for building this tool. 

I'm closing this issue now. If you want to discuss animated GIF support feel free to open another issue.

**Comment by sickill** [comment]
FYI there's "image link" embedding as well as support for oEmbed/Open Graph/Twitter Card: https://asciinema.org/docs/embedding

**Comment by sickill** [comment]
Please try out https://github.com/asciinema/a2gif (I implemented the idea from https://github.com/asciinema/asciinema-player/issues/24#issuecomment-217708694).
