### ISSUE TITLE
Option to save to file instead of upload

### ISSUE THREAD

**Issue by metulburr** [asciinema/asciinema.org#155]
First of all, awesome program. Very sweet.

Could you add an option to save to file instead of uploading. Or linking your youtube account to upload there instead? That is my ultimate goal.

EDIT:
just came across another issue in which is identical.

**Comment by sickill** [comment]
You can now save to a file: http://blog.asciinema.org/post/one-point-o/

**Comment by metulburr** [comment]
Nice. Thanks!!
