### ISSUE TITLE
Handle escape sequence for tmux/screen window name

### ISSUE THREAD

**Issue by vincentbernat** [asciinema/asciinema.org#162]
It is possible to set window name in screen/tmux with `ESC k name ESC \`. See http://web.mit.edu/gnu/doc/html/screen_9.html. Currently, asciinema doesn't handle those escape sequences.

**Comment by sickill** [comment]
asciinema recorder has been rewritten from scratch in Go since you reported this issue so it's possible that this problem doesn't happen anymore. If you will experience this again feel free to reopen this issue.
