### ISSUE TITLE
Ability to revoke API tokens

### ISSUE THREAD

**Issue by grawity** [asciinema/asciinema.org#168]
It seems to be impossible to revoke an API token in case one was leaked (e.g. accidentally serving the entire home directory over HTTP). While the tokens don't give access to private data, they would still allow someone to spam the token owner's profile, so there should be at least a button to revoke all tokens at once.

**Comment by sickill** [comment]
It has just been added. Open your settings page, it's there: https://asciinema.org/user/edit
