### ISSUE TITLE
Unable to use "asciicast:play" event when using iframe directly

### ISSUE THREAD

**Issue by fghaas** [asciinema/asciinema.org#175]
I am trying to embed an asciicast into a reveal.js presentation. What I would like to achieve is asciinema not using its own autoplay (which would cause an asciicast to load and run when the presentation is loaded, not when arriving at the slide where I am trying to run the asciicast). reveal already supports this for YouTube and Vimeo (see https://github.com/hakimel/reveal.js/blob/dev/js/reveal.js#L2753 and https://github.com/hakimel/reveal.js/blob/dev/js/reveal.js#L2760).

Using the default method of embedding asciinema breaks in reveal altogether (the asciinema iframe never gets displayed), so I am using the iframes directly:

```html
<iframe data-autoplay src="https://asciinema.org/api/asciicasts/13761?speed=3&amp;size=medium" id="asciicast-iframe-13761" name="asciicast-iframe-13761" scrolling="yes"></iframe>
```

Now what I am trying to do is use this (https://github.com/fghaas/reveal.js/blob/asciinema-autoplay/js/reveal.js#L2766):

```javascript
// Asciinema embeds
toArray( slide.querySelectorAll( 'iframe[src*="asciinema.org/api/asciicasts/"]' ) ).forEach( function( el ) {
    if( el.hasAttribute( 'data-autoplay' ) ) {
        el.contentWindow.postMessage( '["asciicast:play"]', '*' );
    }
});
```

... which I understand is what the asciinema player expects in the message data: an array whose zeroth element is named `asciicast:play`.

But I find it impossible to trigger the `message` event listener that way, and the player doesn't auto-play. I'm almost certain I'm doing something wrong here, but am stuck and would appreciate some guidance.

**Comment by sickill** [comment]
@fghaas try `postMessage(['asciicast:play'], '*' )` instead.

**Comment by fghaas** [comment]
Thank you; I'll give that a shot at the next opportunity.

**Comment by fghaas** [comment]
Just following up on this, I have finally been able to test this in a reveal.js presentation. Works like charm, thanks very much for the clarification.
