### ISSUE TITLE
src/terminal.c can't compile

### ISSUE THREAD

**Issue by duke-cheng** [asciinema/asciinema.org#182]
Hi,
     terminal.c can't compile correctly, for libtsm update. And do you know how to use libtsm to interpret escape sequence? For example, when I input and edit the bash command, and get the final status when I press enter.

**Comment by duke-cheng** [comment]
Yes, API changed.  But could you tell me how to use libtsm to interpret escape sequence?

**Comment by sickill** [comment]
Read the source of `terminal.c`, it's all there.
