### ISSUE TITLE
Update welcome cast

### ISSUE THREAD

**Issue by nathany** [asciinema/asciinema.org#184]
The cast at https://asciinema.org/ still uses pip install.

**Comment by sickill** [comment]
Thanks for noticing! Will update it.

**Comment by nathany** [comment]
Thanks.

P.S. It is insanely awesome to be able to copy paste text from a "video". I didn't even think about that until I watched the intro. :+1:

**Comment by sickill** [comment]
"Welcome cast" is now updated.
