### ISSUE TITLE
Embedding recordings as gif

### ISSUE THREAD

**Issue by schickling** [asciinema/asciinema.org#187]
This would allow people to embed their asciicasts in README files as animated GIFs.

~~See: https://gist.github.com/lmjabreu/922530~~

(This issue is an addtion to https://github.com/asciinema/asciinema.org/issues/152)

**Comment by sickill** [comment]
Hmm, sorry, but I don't see how this script creates animated gif from asciicast...

**Comment by schickling** [comment]
@sickill you're right. I just copied it from #152

**Comment by sickill** [comment]
@schickling ah, ok. Got it.

**Comment by sedm0784** [comment]
Link to @tav's tool to create gifs from asciinema recordings copied over from #152: [asciinema2gif](https://github.com/tav/asciinema2gif).

**Comment by ELLIOTTCABLE** [comment]
:+1: for this to be included.

(Although I'd personally like to see much higher-quality encodings than `asciinema2gif` appears to currently produce …)

**Comment by sickill** [comment]
@ELLIOTTCABLE yeah, the plan is to have .gifs with the same resolution/quality as the .png we have now.

**Comment by yasoob** [comment]
Hey any update on this issue?

**Comment by AbdealiJK** [comment]
Any updates in this ? I'd like to have this too

**Comment by FuturisticCake** [comment]
I'd also be pretty interested in GIF creation features. (For NPM package READMEs and such things.)

**Comment by sickill** [comment]
Please try out https://github.com/asciinema/a2gif (I implemented the idea from https://github.com/asciinema/asciinema-player/issues/24#issuecomment-217708694).

**Comment by sickill** [comment]
If you append `.gif` to your recording URL now you get instructions on how to generate gif animation for it. Example: https://asciinema.org/a/113463.gif
