### ISSUE TITLE
asciicast tooling in list view

### ISSUE THREAD

**Issue by omaraboumrad** [asciinema/asciinema.org#192]
Hello,

The ability to do the following within the List view would be great facility for the owner:

1) Edit the title of the cast.
2) Make the cast public/private.
3) Delete the cast.

Thank you Asciinema!

**Comment by sickill** [comment]
By "List view" you mean for example a profile page like this https://asciinema.org/~omaraboumrad ?

**Comment by omaraboumrad** [comment]
Yes exactly, I should've been clearer.

**Comment by sickill** [comment]
Got it. Thanks for the suggestion. I agree it would be more convenient, and while I won't make it a high priority for now (other priorities :smile:), I will keep this issue open.

**Comment by sickill** [comment]
I'm closing old issues. Please reopen if you still think this is a valuable feature worth maintaining.
