### ISSUE TITLE
takes very long to execute a command, and ctrl + d doesn't exit the shell in my mac OSX  

### ISSUE THREAD

**Issue by shaunstanislaus** [asciinema/asciinema.org#193]
takes very long to execute a command, and ctrl + d doesn't exit the shell in my mac OSX  

i have done asciinema auth
after i type 'asciinema rec'

i do some commands like brew doctor or some other commands i execute

it takes very long for it to appear

and i can't exit the recording via ctrl+ d or by typing exit.

it is very laggy, may i know why is it so?

**Comment by sickill** [comment]
What terminal and what shell are you using?

**Comment by shaunstanislaus** [comment]
I am using iterm 2 and using bash shell

**Comment by sickill** [comment]
To figure out what's the cause, can you try testing `script` tool? It does similar thing under the hood. Your Mac should have it. Just run `script`, and then try running some commands and seeing if it's slow too. Then finish with `ctrl-d` or type `exit`.

**Comment by shaunstanislaus** [comment]
hmm, strange. after doing script, close terminal and restart, it worked. it uploaded first session to the web.

**Comment by sickill** [comment]
Ok, thanks for reporting back.
