### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by sgoings** [asciinema/asciinema.org#197]
When I try to log into asciinema.org I press the "Log in" button on the top right, add my email address, and press the "Log In" button. I get an email fairly soon after, (though delivery time is quite variable as well) which I click on and then get an asciinema.org page:

>Invalid login link
>
>Your login link is either invalid or has expired.
>
>Login links are valid for 15 minutes. If you think yours might have expired then request a new login link.
>
>If you're copy-pasting the link check if the link hasn't been corrupted by your email client's message formatting.

I have received this error even though I clicked on the email link well well within the 15 minute log in window.

**Comment by sickill** [comment]
What email client are you using? What web browser are you using? Can you send me the screenshot of the email containing the login link that didn't work to support@asciinema.org?

**Comment by sgoings** [comment]
I use Gmail (web client) as my email client. I just tried logging in again and had great success! But I had this problem yesterday, this morning, and shortly before I submitted this issue. I'll attach a screencast to this issue the next time it happens though.

**Comment by sickill** [comment]
Ok, great. Feel free to reopen when it happens again.
