### ISSUE TITLE
Poor error message when username is already taken

### ISSUE THREAD

**Issue by mgedmin** [asciinema/asciinema.org#199]
![ekrano nuotrauka is 2015-09-10 11-54-55](https://cloud.githubusercontent.com/assets/159967/9784250/c80e7bbc-57b2-11e5-9de9-796d14e1ae72.png)

As you can see, my username consists entirely of valid characters.  I think the actual problem is that I used a different email address to login in the past.

**Comment by sickill** [comment]
Oh right, the problem is probably that username is already taken.

**Comment by ELLIOTTCABLE** [comment]
:+1:, I [ran into this too](https://twitter.com/ELLIOTTCABLE/status/660810453447233541).
