### ISSUE TITLE
Docker image for easy deployments

### ISSUE THREAD

**Issue by foobarto** [asciinema/asciinema.org#204]
A docker image that can be easily deployed standalone or in production would be useful.

I've started working on something like that today: https://github.com/foobarto/docker-asciinema-server

Unlike other images for asciinema out there currently, this one does not attempt to run everything in same container. Instead you need to run postgres, redis, sidekiq and rails separately. This however allows for more flexibility. 
If there's interest I could write a docker-compose file that would showcase how to deploy multiple instances of rails behind web proxy (nginx/haproxy/other).

Feel free to integrate this Dockerfile into this repository. The benefit of doing this is that whenever you update this repository it would trigger build of a new docker image on the docker hub.

**Comment by sickill** [comment]
Hey @foobarto!

Thanks for building this! I planned to add Dockerfile to the repository but never got time for that.
I prefer your approach of running a focused, single service containers :+1: 

As for `ADDRESS`, you can already pass `HOST=....` env var 
(https://github.com/foobarto/docker-asciinema-server/blob/master/cfg.rb#L39) so no need for your custom version of `cfg.rb`.

If you send a PR to this repo I'd be very happy to accept and merge it. 
Btw, by having it in the same repo as the code there won't be a need for `git clone` and we can probably just use `ADD . /app`.

**Comment by foobarto** [comment]
I'll start the fork now and send PR later today. I don't think there are any downsides of doing `ADD . / app`, you may want however at some stage add `.dockerignore` file (similar to .gitignore) if it makes sense to exclude some files.

**Comment by foobarto** [comment]
There we go: https://github.com/asciinema/asciinema.org/pull/205

**Comment by foobarto** [comment]
Could you reply here once you have the image on the Docker Hub? I'd like to start using it instead the one I created earlier.

**Comment by sickill** [comment]
https://hub.docker.com/r/asciinema/asciinema.org/

**Comment by vsoch** [comment]
Just want to post the updated links for those that find the thread, since the above is broken:

 - https://hub.docker.com/r/asciinema/asciinema/
 - https://hub.docker.com/r/asciinema/asciinema-server
