### ISSUE TITLE
API to *download* asciicasts

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [asciinema/asciinema.org#206]
Currently, I'm leaving all my `.asciicasts` in a folder, because once I upload them, there doesn't appear to be any way to get them back.

(I'd like to be able to download an `.asciicast`, edit it, and re-upload it later, if I like!)

**Comment by sickill** [comment]
You can download original asciicast file after it has been uploaded: https://asciinema.org/a/29108.json
I should document that somewhere on the site probably ;)

**Comment by sickill** [comment]
There is a Download button on every asciicast page (it points to https://asciinema.org/a/{asciicast-id}.json).
