### ISSUE TITLE
Param 'data-t' is not taken into account

### ISSUE THREAD

**Issue by duckmole** [asciinema/asciinema.org#209]
When I embed an asciinema recording with the param data-t as explain the Sharing & Embedding documentation

```
  <script type="text/javascript" src="https://asciinema.org/a/e5hiuac8dafvij3fzpieqdznp.js?" id="asciicast-e5hiuac8dafvij3fzpieqdznp" async data-t="30"></script>
```
The data-t is not taken into account.

I check very quickly the code and I not see 't' in the list of options :
https://github.com/asciinema/asciinema.org/blob/master/app/assets/javascripts/widget.js#L16

Sorry, I have no time right now, to make a pull request for this issue.

**Comment by sickill** [comment]
Ah, indeed it's missing here.

**Comment by sickill** [comment]
Fixed now.

**Comment by duckmole** [comment]
Thk

**Comment by simonmichael** [comment]
Thanks!
