### ISSUE TITLE
Why does the embed page render incorrectly?

### ISSUE THREAD

**Issue by d33tah** [asciinema/asciinema.org#210]
Take a look here:

http://deetah.jogger.pl/2015/11/20/fuzzowac-co-sie-da/

Why does the embedded video at the end of the article display with wrong height?

**Comment by sickill** [comment]
Ha, that's a good question. The document in the iframe sends the actual player size to the host page via `postMessage`. Looks like it doesn't work for some reason.

**Comment by sickill** [comment]
It actually delivers the message to your host page but the embed script doesn't set the size...

**Comment by sickill** [comment]
Ok, there's a bug. You made this recording public but you used the private URL when embedding. This should of course work fine. Will try to find a fix for that. If you're in a hurry then just use the public URL: `<script type="text/javascript" src="https://asciinema.org/a/26623.js" id="asciicast-26623" async></script>`.

**Comment by sickill** [comment]
Fixed in 466a21a.

**Comment by d33tah** [comment]
Thanks! :)

**Comment by sickill** [comment]
@d33tah Btw, `text-indent: 8px` on your `p` elements pushes the player `div` to the right, as it's treated as yet another block of text inside `p`. Unfortunately nothing can be done to fix that on the player side.
