### ISSUE TITLE
Embedding gists from github in asciicasts description

### ISSUE THREAD

**Issue by ryrych** [asciinema/asciinema.org#211]
First of all, thank you for this great project!

Recently I started recording asciicasts, and found that one feature would make it more approachable—embedding gists / snippets of code.

For example, instead of copy-pasta, or adding a link to the gist, I could store it once and then embed it in asciicast and other places. What do you think?

[example asciicast with link to gist](https://asciinema.org/a/30059)

**Comment by sickill** [comment]
Thanks for the idea. While this could be desirable in some scenarios (like yours), I think in general case it may not be what user would expect. It's easy to imagine someone linking from asciicast to a gist containing long log output or a stack trace. This wouldn't look too good when inlined.

One option would be to make this inlining explicit, opt-in. But right now the description is treated as markdown with no non-standard behavior (just Github flavored markdown) and seems to be good enough for majority of users.

**Comment by ryrych** [comment]
Right, thanks. Unlike regular github `README.md`, any self-hosted jekyll site* can embed javascript asiinema player and embed gists (out of the box).

* jekyll pages hosted on github can embed asciinema player
