### ISSUE TITLE
recording a terminal session with multiple tabs

### ISSUE THREAD

**Issue by luminize** [asciinema/asciinema.org#215]
Hi,

First of all, you have made an awesome package! Thanks for this simple, clutter free way of showing instructions.

I searched your issues but couldn't find if this already has been asked
Would it be possible to switch between tabs on a terminal session?

**Comment by sickill** [comment]
It's not possible because asciinema records stdout of a single process (your shell by default).
If you would like to record a session including several bash instances/windows then you can use record tmux or gnu screen session (some people do exactly this).
