### ISSUE TITLE
404 after entering username for first time

### ISSUE THREAD

**Issue by ant31** [asciinema/asciinema.org#218]
Hi, 

I've just created a new account, when I validated my username I got redirected to this page:

`https://asciinema.org/unauthenticated_user`

The account have been correctly created 

usename: ant31

**Comment by sickill** [comment]
What browser are you using? Do you have non-standard settings like disable cookies, extensions blocking some browser features?

Are you able to login now?

**Comment by ant31** [comment]
Yes the account have been created without any other action. 
Only the redirection failed.

I accept cookies, I'm using chrome with adblock

**Comment by piotrgo** [comment]
I just had the same issue. Mac, Chrome, Adblock, nothing fancy.

**Comment by sickill** [comment]
This is interesting... Well, I'm going to redesign authentication soon, hopefully this will be no issue then 💥
