### ISSUE TITLE
Bold attribute doesn't display on asciinema.org playback

### ISSUE THREAD

**Issue by mrhmouse** [asciinema/asciinema.org#219]
Looks like the bold attribute is recorded properly. It appears in playback in a terminal, and in the thumbnail on asciinema.org - just not in playback on the site.

Demo recording: https://asciinema.org/a/38236

**Comment by sickill** [comment]
@mrhmouse thanks for reporting. Looks good now.

**Comment by mrhmouse** [comment]
Awesome, thank you!
