### ISSUE TITLE
Allow configuring Redis

### ISSUE THREAD

**Issue by dasJ** [asciinema/asciinema.org#224]
It would be nice if I could configure the Redis connection so I can connect to my existing Redis cluster instead of hosting a single node on my Asciinema server.

**Comment by sickill** [comment]
You can set `REDIS_URL=redis://1.2.3.4:6379` environment variable. It should be set for both Rails and Sidekiq process. More info here: https://github.com/mperham/sidekiq/wiki/Using-Redis
