### ISSUE TITLE
Docker image is missing wget 1.16

### ISSUE THREAD

**Issue by fruch** [asciinema/asciinema.org#230]
without it preview images aren't working

RuntimeError in AsciicastsController#show
Couldn't generate image from /app/uploads/asciicast/file/4/asciicast.json: asciinema-player.js missing, downloading ... wget: unrecognized option '--show-progress' Usage: wget [OPTION]... [URL]... Try `wget --help' for more options.

**Comment by fruch** [comment]
and even then it's not working...

**Comment by fruch** [comment]
Couldn't generate image from /app/uploads/asciicast/file/4/asciicast.json: Input is local file, starting server on port 4444... Loading player page... console.log: Failed to pre-load Powerline Symbols font Couldn't get geometry of requested DOM element Shutting down local server...

**Comment by sickill** [comment]
I've updated Dockerfile to symlink player files - thanks to this it doesn't try to download them with wget.

**Comment by fruch** [comment]
And does the preview works like that ?

**Comment by sickill** [comment]
I've just merged lots of improvements to this docker image into master, including fixes for this issue.
