### ISSUE TITLE
dim/faint not working properly

### ISSUE THREAD

**Issue by uppfinnarn** [asciinema/asciinema.org#236]
I'm not 100% sure if this is a bug on asciinema.org or [asciinema-player](https://github.com/asciinema/asciinema-player).

The dim/faint color attribute doesn't show up properly in the web player.

Running this script:

```bash
#!/bin/bash

printf "\n"
printf "    _   __                           __   \e[2m______      _       __ \e[0m\n"
printf "   / | / /___  _________ ___  ____ _/ /  \e[2m/ ____/___ _(_)___  / /_\e[0m\n"
printf "  /  |/ / __ \/ ___/ __ ´__ \/ __ ´/ /  \e[2m/ /_  / __ ´/ / __ \/ __/\e[0m\n"
printf " / /|  / /_/ / /  / / / / / / /_/ / /  \e[2m/ __/ / /_/ / / / / / /_  \e[0m\n"
printf "/_/ |_/\____/_/  /_/ /_/ /_/\__,_/_/  \e[2m/_/    \__,_/_/_/ /_/\__/  \e[0m\n"
printf "\n"
```

Produces the expected output in a terminal:

<img width="465" alt="screen shot 2017-02-22 at 19 24 56" src="https://cloud.githubusercontent.com/assets/428026/23226388/a7b263a8-f935-11e6-8a15-5f74b8dee9c9.png">

<img width="464" alt="screen shot 2017-02-22 at 19 28 06" src="https://cloud.githubusercontent.com/assets/428026/23226391/ab6d700a-f935-11e6-984c-69f0ff1f699f.png">

But not on asciinema.org:
- black/white: https://asciinema.org/a/4dc8adqp6ydgz4rcph4zvuucb
- colored: https://asciinema.org/a/8muthjs1m0bcbo6f1c4tp8kt1

**Comment by sickill** [comment]
Yes, asciinema-player doesn't support `\e[2m` (yet). Thanks for bringing this up.

**Comment by uppfinnarn** [comment]
Should I repost this on asciinema-player?

**Comment by sickill** [comment]
That would be great, thanks!

**Comment by uppfinnarn** [comment]
There: https://github.com/asciinema/asciinema-player/issues/52
