### ISSUE TITLE
Losing videos on private server after reboot

### ISSUE THREAD

**Issue by Akillinwow** [asciinema/asciinema.org#237]
I can create recordings and send them to my private server successfully (great instructions by the way for the server setup!). However, after I reboot my server when I got to the same link, I cant play the video anymore. I can create new recordings and they work, until the next reboot. 

Is there a certain way to start my private server after a reboot so old videos will work again?

I run the following command to get my server going after a reboot:

docker-compose up -d asciinema

Thanks.

**Comment by sickill** [comment]
After reboot, are you getting 404 page or the server isn't running at all?

**Comment by Akillinwow** [comment]
The page works fine. I can get to the web page after I run the command I mentioned above and I am able to load new videos. But when I use a link created for any video created before the reboot, when I get to page and press play, it just spins and never plays.

**Comment by sickill** [comment]
I see, this looks to me like problem with Docker's volumes. I don't deploy asciinema with Docker so need to try that first.

**Comment by Akillinwow** [comment]
Should I try to install a server with the "manual Setup" instructions? Is that how asciinema server is really deployed?

**Comment by Akillinwow** [comment]
I figured it out..it was my bad. So when I initially setup my asciinema server using the docker-compose.yml file, I didnt update the volumes section in that file to NOT point to /tmp directory. So everytime I rebooted, I was loosing anything I had created.

 I updated each of the volumes to point to a file system I dedicated for all this and now the ascii casts are staying put!

**Comment by sickill** [comment]
Great!
