### ISSUE TITLE
resolution error on login

### ISSUE THREAD

**Issue by jaxxstorm** [asciinema/asciinema.org#238]
I'm running the app in Kubernetes, and when trying to login I'm getting an error:
```
SocketError in LoginsController#create
```
```
getaddrinfo: Name or service not known
```

The error seems to be coming from this code:

```
def self.delay_login_request(user_id, token)
    delay.login_request(user_id, token) <--- here
  end

  def login_request(user_id, token)
```

This should be fairly easy to fix, but I don't know what it's trying to resolve? I tried to set `HOST` to `localhost:3000` but that didn't seem to resolve this issue.

Any ideas?

**Comment by jaxxstorm** [comment]
I tcpdump'ed the connection and discovered I'd misnamed my redis service. Once I had a valid redis url, it worked.

**Comment by sickill** [comment]
Ah, right, so it couldn't enqueue email send job. Glad you figured it out 👍
