### ISSUE TITLE
Strange artifacts when recording vim session; only when played in terminal

### ISSUE THREAD

**Issue by mattdeckard** [asciinema/asciinema.org#239]
In a terminal only, when playing back a session that involves running `vim`, the terminal outputs some characters when `vim` is opened and after `asciinema` is done running. I believe this is due to `asciinema` recording some terminal control sequences that encode requests to the terminal for information. It also plays back these requests which causes the responses to be doubled up (i.e. both the recorded responses and the real-time responses to the played-back requests are seen)

Here is the asciicast illustrating this effect:
https://asciinema.org/a/b7oiev7osmfxggs4nh0heyxxo
Again, note that you won't see the effect when you run this in the browser. You will have to download it and run it in a terminal with `asciicast play`

In this case, the offending control sequences seem to be `CSI 6 n` (CPR) and `CSI > c` (Send Secondary DA)

I'm honestly not sure how best to handle/fix this. Stripping out any "request" escape sequences (i.e. DSR, Send DA, DECRQM, DECREQTPARM, etc) when playing back sessions seems reasonable. A reference for these sequences can be found at: http://invisible-island.net/xterm/ctlseqs/ctlseqs.html

**Comment by mattdeckard** [comment]
P.S. Those offending control sequences show up in the JSON file as `\u0013]6n` and `\0013]>c` respectively. I've verified that stripping both of them out of the JSON causes the problem to go away, but stripping only one or the other still causes problems.

**Comment by mattdeckard** [comment]
Now that I realize there's a separate repo for the recorder app, this is probably just a duplicate of https://github.com/asciinema/asciinema/issues/108 and/or https://github.com/asciinema/asciinema/issues/192. I'll close this and add any useful information I can to those tickets.

**Comment by sickill** [comment]
@mattdeckard thanks!
