### ISSUE TITLE
Playback in terminal: Ability to resize terminal to match recording

### ISSUE THREAD

**Issue by mattdeckard** [asciinema/asciinema.org#240]
When playing back a JSON recording, if your terminal is not the same width/height as the recording, the effects can be strange. Since the width and height are already stored in the JSON file, it should be pretty easy to at least give an option to resize the terminal to the recording's width and height during playback, if not make that the default behavior.

**Comment by mattdeckard** [comment]
I have a simple bash script that accomplishes this in a gist: https://gist.github.com/mattdeckard/246edaa833191f69862a8591498e09c2#file-fix-asciicast

**Comment by sickill** [comment]
@mattdeckard thanks for bringing this up! I wasn't aware that you can do that. I've opened an issue for this in asciinema recorder repo: https://github.com/asciinema/asciinema/issues/198
