### ISSUE TITLE
Broken preview image is being generated

### ISSUE THREAD

**Issue by psprint** [asciinema/asciinema.org#242]
Hello,
following image is said to be broken by Firefox and Chrome: https://asciinema.org/a/112367.png

It is the image used by "Share" link, in markdown embed snippet, of this video: https://asciinema.org/a/112367

Chrome generates 503 error, Firefox says the image contains errors.

**Comment by sickill** [comment]
Thanks for reporting. There was a temporary issue with PNG generator. It's working again.

**Comment by psprint** [comment]
Thanks
