### ISSUE TITLE
Support for asciicast:play window message removed

### ISSUE THREAD

**Issue by fghaas** [asciinema/asciinema.org#250]
I used the `asciicast:play` window event with much success from [reveal.js](/hakimel/reveal.js) a couple of years ago (see #175). I am trying to figure out where it went, because it no longer seems to be available the way it was.

- `app/views/layouts/raw.html.slim` (which contained the necessary functionality at the time) was renamed to `app/views/layouts/bare.html.slim` in edca76233de1d24e114d52da95170eee4edcfb45.
- Then, `bare.html.slim` became `show.html.slim` in 06c19adaab706411b2fbcdf98059cedf31966bd6.
- In baf1c96c7e9d3cdcb7811b503f7bd4f77da26596, it was decided that there is "no need for jQuery inside of an iframe", and in the process the `$('.start-prompt').click();` was replaced with a TODO.
- Then, that TODO was dropped a couple of months ago as "dead code", in 5992e9b2aa5003b9d41a0c7815ee95bad4ad7b67.

Now, there's no trace of the `asciicast:play` event left in the code, so what can I do to bring that functionality back?

**Comment by sickill** [comment]
Hej Florian! It seems we lost it indeed. Like you found out, there was a change of loosely related changes. And to be honest, I thought "nobody uses this anyway", as this functionality wasn't officially documented. My bad 😬 

Let me take a look at this!

**Comment by fghaas** [comment]
Thanks for looking into this. To be fair, I never managed to get the functionality into reveal.js proper (see discussion in hakimel/reveal.js#1382).

By the way, since you're already considering bringing it back. To just cover the reveal.js use case, it posts a generic `slide:start` message to *all* embedded iframes, so if you want to add that in addition to bringing back the old `asciicast:play` event, then reveal could even auto-start playback without modifications at all (see [here](https://github.com/hakimel/reveal.js/blob/master/js/reveal.js#L3262)).

**Comment by sickill** [comment]
Thanks for bringing up reveal.js sent events, this is cool.

Anyway, I've brought back the original event handling + added reveal.js support in #251.

**Comment by sickill** [comment]
Fixed in #251
