### ISSUE TITLE
play in sync with a screencast

### ISSUE THREAD

**Issue by albfan** [asciinema/asciinema.org#254]
One of the most frustrating things from tech videos is to see a terminal executing complex commands and cannot copy paste them directly. asciinema/ttyrec solves that, but videos are useful to see more things than just commands.

Say I'm showing a screencast about using gdb debugging a draw editor. it shows draw editor and a terminal splitted in four panels:

1. gdb session
2. gdb source execution point
3. running program debugged
4. logging output for program executed

screencat want to show debugging how code paints a circle and how it detect an area to fill with color, bla bla bla

I want to see that video but at the same time I want to share asciicast for those 4 terminals.

It will be just add an embedded video like

https://youtu.be/QtRQmjBA3b8?t=3m54s

```
<iframe width="560" height="315" src="https://www.youtube.com/embed/QtRQmjBA3b8" frameborder="0" allowfullscreen></iframe>
```

which is costless, and asciinema has lot of space right now on its screen for that. Is just a matter of synchronize time stamp for screencast and asccicast.

Identify which asciicast is each terminal pane is something that user needs to realize by himself (don't expect asciinema to provide an overlay over screencast (but youtube annotations can provide that https://youtu.be/vEq1fw4yHE8?t=1m49s)

thoughts?

**Comment by sickill** [comment]
I think this may be useful to your use-case: https://github.com/asciinema/asciinema-player#controlling-the-player-programmatically

You can self-host the player on your page, and write some glue JS code to synchronize asciinema player with youtube player.

**Comment by albfan** [comment]
Yes I'm sure. Just want to know the asciinema perspective. I want a central point to share screencast with asciicast, not my own particular page

So is not something usefu for asciinema?

**Comment by sickill** [comment]
Correct. We don't plan integration with youtube on asciinema.org.

**Comment by albfan** [comment]
Thanks

**Comment by albfan** [comment]
FTR: https://github.com/dhobsd/castty and https://9vx.org/~dho/term/index.html are mostly it. Just need to change audio to video https://www.w3schools.com/tags/ref_av_dom.asp and maybe paint some semitransparent parallelepiped in case some reference is needed
