### ISSUE TITLE
Service 'sidekiq' failed to build

### ISSUE THREAD

**Issue by Flipez** [asciinema/asciinema.org#260]
When trying to install asciinema sidekiq failed to build since java can not be downloaded or extracted. 

`ERROR: Service 'sidekiq' failed to build: The command '/bin/sh -c wget --quiet -O /opt/jdk-8u111-linux-x64.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz &&     tar xzf /opt/jdk-8u111-linux-x64.tar.gz -C /opt &&     rm /opt/jdk-8u111-linux-x64.tar.gz &&     update-alternatives --install /usr/bin/java java /opt/jdk1.8.0_111/bin/java 1000' returned a non-zero code: 8`

OS: `Linux example.host 4.4.0-77-generic #98-Ubuntu SMP Wed Apr 26 08:34:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Flipez** [comment]
I've split up the commands and  removed the --quite to get a bit more output

```
Step 12 : RUN wget -O /opt/jdk-8u111-linux-x64.tar.gz --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz

 ---> Running in 8e8eda4e6fd9
--2017-06-01 10:17:51--  http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz

Resolving download.oracle.com (download.oracle.com)... 2.20.189.169, 2.20.189.177
Connecting to download.oracle.com (download.oracle.com)|2.20.189.169|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz [following]
--2017-06-01 10:17:51--  https://edelivery.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz

Resolving edelivery.oracle.com (edelivery.oracle.com)... 104.108.49.101, 2a02:26f0:64:183::2d3e, 2a02:26f0:64:18f::2d3e

Connecting to edelivery.oracle.com (edelivery.oracle.com)|104.108.49.101|:443... connected.

HTTP request sent, awaiting response... 302 Moved Temporarily

Location: http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz?AuthParam=1496312391_959b15706bd6c9f69a38d9342e99ab27 [following]
--2017-06-01 10:17:52--  http://download.oracle.com/otn-pub/java/jdk/8u111-b14/jdk-8u111-linux-x64.tar.gz?AuthParam=1496312391_959b15706bd6c9f69a38d9342e99ab27

Connecting to download.oracle.com (download.oracle.com)|2.20.189.169|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-06-01 10:17:53 ERROR 404: Not Found.
```

**Comment by Flipez** [comment]
@sickill Do you think it would be an appropriate fix to provide a short script which parses the latest jdk version (since there is no rss  feed or latest link) to avoid to break the Dockerfile periodically.

This could be done with Python directly within the container. Instead of running the download and tar you would then only trigger the script.

**Comment by sickill** [comment]
@Flipez thanks for the suggestion. I think we won't need to manually download JDK soon. Docker 17.06 (to be released within days) supports multi-stage builds, where we can do several `FROM` stages, and base one of them on one of the official JDK images. I did this for asciicast2gif, looks very promissing: https://github.com/asciinema/asciicast2gif/pull/16
