### ISSUE TITLE
Switch license to Apache v2.0

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema.org#264]
I'd like to switch the license of this project to Apache v2.0 license.

Do I have your permission for doing that @foobarto, @mhor, @Flipez? (the project includes your contributions so I need your permission to re-license them)

**Comment by foobarto** [comment]
Yes. No objections here.

I would think you as the main author could make that decision yourself.

**Comment by sickill** [comment]
@foobarto thanks :) (I think so but asking wouldn't hurt)

**Comment by mhor** [comment]
Yes no problem

**Comment by sickill** [comment]
@Flipez ping ;)

**Comment by sickill** [comment]
@mhor 👍

**Comment by Flipez** [comment]
@sickill Sure, no problem for me ;)
