### ISSUE TITLE
[Feature request] Add some way to detect asciinema

### ISSUE THREAD

**Issue by legolord208** [asciinema/asciinema.org#267]
Hey! Imagine my bashrc has some message printing on startup? Yeah I kinda wouldn't like that in my asciinema cast. So hey, here's an idea.

Set some environment variable before running the shell! [Sample code](https://stackoverflow.com/a/8301399)  

This would allow detecting asciinema and then not print the message :+1:

**Comment by sickill** [comment]
It's already there: https://asciinema.org/docs/usage

**Comment by legolord208** [comment]
I officially feel stupid now lol
