### ISSUE TITLE
Docker guide points to 404

### ISSUE THREAD

**Issue by hzpc-joostk** [asciinema/asciinema.org#277]
The link to the guide to installing the asciinema.org web app on Docker hub points to a nonexisting URL.

See https://hub.docker.com/r/asciinema/asciinema.org/

> [asciinema web app install guide](https://hub.docker.com/r/asciinema/asciinema.org/docs/INSTALL.md)

**Comment by hzpc-joostk** [comment]
It could (should?) point to https://github.com/asciinema/asciinema.org/blob/master/docs/INSTALL.md

**Comment by sickill** [comment]
@hzpc-joostk we have relative URL in our README which works on Github but apparently is wrong when displayed on Docker hub. Let's change it to the full URL like you suggested. Could you send a PR?

**Comment by hzpc-joostk** [comment]
Links are fine in the readme of Docker Hub: https://hub.docker.com/r/asciinema/asciinema.org/

This issue can be closed. :) Glad I could help!

**Comment by sickill** [comment]
Thanks!
