### ISSUE TITLE
Self hosted increasing asciicast upload size

### ISSUE THREAD

**Issue by RelativePrime** [asciinema/asciinema.org#285]
When running self hosted instance containers, where is the asciicast upload size limit defined?

**Comment by sickill** [comment]
I just added new section to Docker installation doc about this: https://github.com/asciinema/asciinema.org/blob/master/docs/INSTALL.md#customizations

**Comment by RelativePrime** [comment]
Thanks for adding the config guide!

My lack of docker foo is certainly to blame, but modifying client_max_body_size in docker/nginx/asciinema.conf and rebuilding didn't seem to do it. 

Doing docker exec -it b7819586d6b7 bash (the newly built container) I see the values appears to have been increased:

root@b7819586d6b7:/app# grep -R client_max /etc/nginx/*
/etc/nginx/sites-available/default:    client_max_body_size 75m;
/etc/nginx/sites-enabled/default:    client_max_body_size 75m;

But I still receive "Upload failed: Sorry, your asciicast is too big." when attempting to upload a 40m asciicast file.

Any hints to help point me in the right direction?

**Comment by RelativePrime** [comment]
Rebuilt container, trying both greater values and a value of 0 in 

root@5cb4f365b987:/app# grep -r client_max /etc/nginx/*
/etc/nginx/sites-available/default:    client_max_body_size 0;

tcpdump confirms nginx is still returning 413 on the upload attempt

```
18:55:05.585672 IP b7819586d6b7.http > lost.host.com.42113: Flags [P.], seq 1:262, ack 46553379, win 8298, options [nop,nop,TS val 177815260 ecr 2420352911], length 261: HTTP: HTTP/1.1 413 Request Entity Too Large
E..9.0@.@.Q^.........P...-.~...... j1\.....

.>..C..HTTP/1.1 413 Request Entity Too Large
Server: nginx/1.10.3 (Ubuntu)
Date: Thu, 31 Aug 2017 18:55:05 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 21
Connection: close
cache-control: max-age=0, private, must-revalidate
```
Plenty of room on the filesystem available. 

Does an explicit value need set in unicorn.rb, etc?

**Comment by sickill** [comment]
Ha, not in unicorn.rb, but in Phoenix endpoint config. So the limit is on nginx and also in the application server. I just realized that.

So `Plug.Parsers` has a default max body size of 8MB.

You need to change this: https://github.com/asciinema/asciinema.org/blob/master/lib/asciinema_web/endpoint.ex#L25-L28

To this:

```elixir
  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison,
    length: 75_000_000
```

**Comment by RelativePrime** [comment]
That works, thanks!

**Comment by ku1ik** [comment]
FYI I just made configuration of the upload size limit much easier, via the `UPLOAD_SIZE_LIMIT` env variable. See here: https://docs.asciinema.org/manual/server/self-hosting/configuration/#upload-size-limit
