### ISSUE TITLE
Private recordings

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema.org#34]

**Comment by hardipe** [comment]
+1, really waiting for this feature!
It would definitely expand your target market in the form of companies sharing top-secret terminal playbacks among their staff.

I would pay for this feature as well.

**Comment by KenjiHollis** [comment]
:+1: :+1: :+1: 

I would _PAY FOR THIS FEATURE_.

**Comment by nathany** [comment]
I'm with @fusiondog on this one. I'd just run a local copy as mentioned in the FAQ.

https://asciinema.org/docs/faq

**Comment by sickill** [comment]
Good news! Private asciicasts just landed for everyone: http://blog.asciinema.org/post/private/

**Comment by hardipe** [comment]
That's wonderful news! I am very thankful for this feature.

It appears that you did not introduce any paid model for this. I recommend you also think of a way to monetize asciinema's usage in the future to raise funds for further development. It's a cool project!

**Comment by sickill** [comment]
@hardipe Enjoy! No, no paid model this time. Maybe some day, we'll see. As for private asciicasts I realized that this is a really essential thing, and everyone who wants to try asciinema shouldn't be forced to auto-publish their first recordings.
