### ISSUE TITLE
Pause when window loses focus

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema.org#60]

**Comment by sickill** [comment]
@marcellodesales since yesterday you can also pause with a `space bar`, and toggle full screen mode with the `f` key.

**Comment by marcellodesales** [comment]
@sickill that's awesome! I will try that!

**Comment by sickill** [comment]
There is now dedicated issues in player's repo for this: https://github.com/asciinema/asciinema-player/issues/6
