### ISSUE TITLE
Display recorded input in an overlay

### ISSUE THREAD

**Issue by sickill** [asciinema/asciinema.org#84]
When recorded input stream is available let's display it in some kind of an overlay. Handy for tutorials where you want to see what keys are being pressed.

**Comment by nathany** [comment]
Could this just be a separate tool running (displaying somewhere on screen) that then just happens to be recorded?

**Comment by sickill** [comment]
Very first versions of asciinema from 2012 had stdin (keystrokes) recording but it was dropped long time ago. So there's nothing to show at the moment :)

And yeah, what you described could work. You're thinking about displaying extra text inside of terminal, like tmux or screen do it with their status bars for example? If you find such a tool let me know!

**Comment by sickill** [comment]
I guess you could even script tmux to display "subtitles" in its status bar. Then record the whole thing :)

**Comment by jez** [comment]
@sickill Do you have any idea of how you'd go about implementing that tmux solution you hinted at above? I've been meaning to make some Vim screen casts where showing what keys you press is the essence of the problem.

**Comment by sickill** [comment]
@jez I don't have any particular tmux-based solution on my mind but I know tmux is very scriptable so there may be some way to do that.

**Comment by Kraymer** [comment]
Please see #105 about a tmux-based solution.
